external_components:
  - source:
      type: git
      url: https://github.com/DpunktS/seplos_v3_sniffer

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200

sensor:
  - platform: seplos_parser
    bms_count: 2

