external_components:
  - source:
      type: git
      url: https://github.com/DpunktS/seplos_v3_sniffer

esp32:
  board: esp32dev
  framework:
    type: arduino

uart:
- id: seplos
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200
  rx_buffer_size: 2048


seplos_parser:
  id: seplos_v3
  bms_count: 2  # Anzahl der Akku's (max. 16)
  uart_id: seplos  # SeplosParser verwendet diese UART ID
  
sensor:
 # bms0
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 pack_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 current
    unit_of_measurement: "A"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 remaining_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 total_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 total_discharge_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 0
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 soc
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 soh
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cycle_count
    unit_of_measurement: "cycles"
    accuracy_decimals: 0
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 average_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 average_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 max_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 min_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
        - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 max_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 min_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 maxdiscurt
    unit_of_measurement: A
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 maxchgcurt
    unit_of_measurement: A
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_1
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_2
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_3
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_4
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_5
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_5
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_6
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_7
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_8
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_9
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_10
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_11
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_12
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_13
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_14
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_15
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_16
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_temp_1
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_temp_2
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_temp_3
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 cell_temp_4
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 case_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 power_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
 # bms1
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 pack_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 current
    unit_of_measurement: "A"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 remaining_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 total_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 total_discharge_capacity
    unit_of_measurement: "Ah"
    accuracy_decimals: 0
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 soc
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 soh
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cycle_count
    unit_of_measurement: "cycles"
    accuracy_decimals: 0
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 average_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 average_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 max_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 min_cell_voltage
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
        - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 max_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 min_cell_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 maxdiscurt
    unit_of_measurement: A
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 maxchgcurt
    unit_of_measurement: A
    accuracy_decimals: 2
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_1
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_2
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_3
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_4
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_5
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_5
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_6
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_7
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_8
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_9
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_10
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_11
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_12
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_13
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_14
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_15
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_16
    unit_of_measurement: V
    accuracy_decimals: 3
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_temp_1
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_temp_2
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_temp_3
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 cell_temp_4
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 case_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms1 power_temp
    unit_of_measurement: °C
    accuracy_decimals: 1
    filters:
      - throttle: 5s

